# --- Dependencies مرحلہ ---
- name: Get Dependencies (flutter pub get)
  # working-directory: ./DigitalWaqt_Azan_Full # ❌ یہ لائن ہٹا دیں
  run: flutter pub get
  shell: /bin/sh -c "{0}" 

# --- Build مرحلہ ---
- name: Build Android APK
  # working-directory: ./DigitalWaqt_Azan_Full # ❌ یہ لائن ہٹا دیں
  run: flutter build apk --release
  shell: /bin/sh -c "{0}"
